In [8]:
import pandas as pd
from sklearn.datasets import load_iris
from neo4j import GraphDatabase

In [2]:
# Load the Iris dataset
iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
# Rename columns
data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
data['target'] = iris.target
data

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [3]:
# Separate the data by class
class_0 = data[data['target'] == 0]
class_1 = data[data['target'] == 1]
class_2 = data[data['target'] == 2]

# Create the subdataset with 50 samples (17 samples per class)
subdataset_50 = pd.concat([class_0.sample(17, random_state=42), 
                           class_1.sample(17, random_state=42), 
                           class_2.sample(16, random_state=42)])

# Create the subdataset with 100 samples (33 samples per class)
subdataset_100 = pd.concat([class_0.sample(33, random_state=42), 
                            class_1.sample(33, random_state=42), 
                            class_2.sample(34, random_state=42)])

# The full dataset is the entire Iris dataset (150 samples)
subdataset_full = data

# Display the class distributions for each subdataset
print("Subdataset 50 samples class distribution:\n", subdataset_50['target'].value_counts())
print("Subdataset 100 samples class distribution:\n", subdataset_100['target'].value_counts())
print("Full dataset class distribution:\n", subdataset_full['target'].value_counts())

Subdataset 50 samples class distribution:
 target
0    17
1    17
2    16
Name: count, dtype: int64
Subdataset 100 samples class distribution:
 target
2    34
0    33
1    33
Name: count, dtype: int64
Full dataset class distribution:
 target
0    50
1    50
2    50
Name: count, dtype: int64

In [4]:
# "First Create an empty database, within a project"

uri = "bolt://localhost:7687"
username = "neo4j" # username for Neo4j, most probably is Neo4j, if you did not change while installing Neo4j Desktop
password = "eigen1234" # Password for database.
database_name = "d2.iris"  # Database name

driver = GraphDatabase.driver(uri, auth=(username, password))

In [5]:
def check_connection():
    try:
        # Establish a session with the specified database
        with driver.session(database=database_name) as session:
            # Run a simple query to check the connection
            result = session.run("RETURN 'Connection to database successful' AS message")
            for record in result:
                print(record["message"])
    except Exception as e:
        print("Error connecting to the database:", e)

# Call the check_connection function
check_connection()

Connection to database successful

In [6]:
# Function to create nodes in the specified database with a dynamic label
def create_nodes(data, driver, label):
    try:
        # Establish a session with the specified database
        with driver.session(database=database_name) as session:
            for _, row in data.iterrows():
                # Create a dynamic dictionary for properties
                properties = row.to_dict()
                # Prepare the Cypher query with a dynamic label
                query = f"CREATE (n:{label} {{"
                query += ', '.join([f"{key}: ${key}" for key in properties.keys()])
                query += "})"
                
                # Run the query with properties
                session.run(query, **properties)

    except Exception as e:
        print("Error during node creation:", e)
    finally:
        # Close the driver
        driver.close()

In [7]:
# For subdataset_50
create_nodes(subdataset_50, driver, 'Dataset2_50_iris')

# For subdataset_100
create_nodes(subdataset_100, driver, 'Dataset2_100_iris')

# For the full dataset (150 samples)
create_nodes(subdataset_full, driver, 'Dataset2_full_iris')

/var/folders/5m/3t1ykjr55_555tllby0d28j00000gn/T/ipykernel_61301/2213674648.py:5: DeprecationWarning: Using a driver after it has been closed is deprecated. Future versions of the driver will raise an error.
  with driver.session(database=database_name) as session: